version: "3.8"
services:
  backend:
    build: ./Backend/Backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./Backend/Backend/uploads:/app/uploads

  frontend:
    build: .
    ports:
      - "5173:80"
    depends_on:
      - backend