version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bandupdb
      MYSQL_USER: bandupuser
      MYSQL_PASSWORD: banduppass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./Backend/Backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bandupdb
      - SPRING_DATASOURCE_USERNAME=bandupuser
      - SPRING_DATASOURCE_PASSWORD=banduppass
    volumes:
      - ./Backend/Backend/uploads:/app/uploads
    depends_on:
      - db

  frontend:
    build: .
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data: