version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bandupdb
      MYSQL_USER: bandupuser
      MYSQL_PASSWORD: banduppass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: maven:3.9.6-eclipse-temurin-21
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bandupdb
      - SPRING_DATASOURCE_USERNAME=bandupuser
      - SPRING_DATASOURCE_PASSWORD=banduppass
    volumes:
      - ./Backend/Backend:/app
      - ./Backend/Backend/uploads:/app/uploads
    command: sh -c "mvn install -DskipTests && mvn spring-boot:run"
    depends_on:
      - db

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: